### ISSUE TITLE
No README

### ISSUE THREAD

**Issue by BrziHR** [jspajic/uum2019#1]
Hi, 

You are missing a README. A README is a vital part of a git repo. A README is a text file that introduces and explains a project. It contains information that is commonly required to understand what the project is about.

**Comment by jspajic** [comment]
Puši kurac

**Comment by BrziHR** [comment]
Weird flex but ok

**Comment by jspajic** [comment]
Dear Petar, check readme now.

**Comment by BrziHR** [comment]
I like it.
